[REF] reset minlength password

diff --git a/zshconf/db_odoo b/zshconf/db_odoo
--- a/zshconf/db_odoo
+++ b/zshconf/db_odoo
@@ -211,6 +211,13 @@ function db_odoo_disable_users_totp() {
         echo "Error: Failed to disable TOTP" >&2
         return 1
     }
+
+    echo "Disable auth_password_policy.minlength"
+    docker_psql "${DB_USER}" "${DB_PASSWORD}" -d "${db_name}" \
+        -c "DELETE FROM ir_config_parameter WHERE key LIKE '%auth_password_policy.minlength%';" || {
+        echo "Error: Failed to disable minlegth password" >&2
+        return 1
+    }
 }
 
 function db_odoo_disable_customziation() {
